services:
  pocketbase:
    build:
      context: ../..
      dockerfile: benchmark-sets/basic-js-v2/shared/pocketbase-go/Dockerfile
      args:
        GO_IMAGE: ${POCKETBASE_GO_IMAGE}
    ports:
      - 8090:8090
    volumes:
      - data:/pb/pb_data
    restart: unless-stopped

volumes:
  data:
